name: Build

on:
  push:
    paths:
      - 'include/**'
      - 'src/**'
      - 'CMakeOptions.cmake'
      - 'cmake/**'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'CMakeOptions.cmake'
      - 'cmake/**'
      - '.github/workflows/build.yml'

env:
  BUILD_TYPE: Release

  ENABLE_LOG: "OFF"
  ENABLE_BENCHMARK: "OFF"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            name: Linux
          - os: windows-latest
            name: Windows
          - os: macos-latest
            name: macOS

    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up build environment (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Set up build environment (macOS)
      if: runner.os == 'macOS'
      run: |
        # Ensure Xcode command line tools are available
        xcode-select --install 2>/dev/null || true

    - name: Configure CMake
      run: cmake -B "${{ github.workspace }}/build" -DCMAKE_BUILD_TYPE="${{ env.BUILD_TYPE }}" -DENABLE_LOG="${{ env.ENABLE_LOG }}" -DENABLE_BENCHMARK="${{ env.ENABLE_BENCHMARK }}"

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }} --parallel
